# Generated by Django 2.2.16 on 2022-06-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220607_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
    ]
